### ISSUE TITLE
Generate on a trained model

### ISSUE THREAD

**Issue by ruisi-su** [Yinghao-Li/GuiGen#2]
Hi, thanks for the continued support of this project! I extend a bit upon using a pre-trained embedding for the text pass, and I have trained a model successfully. However, upon generating the paraphrases, I am hitting an error:
```
Traceback (most recent call last):
  File "txt_generate.py", line 137, in <module>
    main()
  File "txt_generate.py", line 122, in main
    path_mask=path_mask_batch,
  File "/home/ubuntu/research/ruisi/GuiGen/TextGen/Generator.py", line 146, in inference
    dec_beam.forward(txt_prob=txt_prob)
  File "/home/ubuntu/research/ruisi/GuiGen/TextGen/Beam.py", line 73, in forward
    sorted_prev_word_seq = self._txt_seq[prev_beam_indices]
IndexError: tensors used as indices must be long, byte or bool tensors
```
I have modified the `run_txt_generate.sh` with the proper model name, and conditioned line 49 and 51 on `cuda`. Could you please help me figuring out what went wrong?

**Comment by Yinghao-Li** [comment]
Hi Ruisi,

It seems that there is something wrong with the type of `prev_beam_indices`. I'm not sure if this is caused by the difference in package version or other reasons. Can you post the value of `prev_beam_indices` and its type?

**Comment by ruisi-su** [comment]
@Yinghao-Li Sure! Thanks for the fast reply. Below is the `prev_beam_indices`:
```
tensor([0.3876, 0.2494, 0.6094, 0.8347, 0.7333, 0.3221, 0.0942, 0.2389])

tensor([ 6156,  3961,  9679, 13259, 11648,  5117,  1496,  3795]) <-- best_scores_id
15884 <- n_vocab
```
I am running on `pytorch==1.8.1+cu111` with `python=3.7.12`

**Comment by Yinghao-Li** [comment]
It seems that Pytorch changed the behavior of `div` operator (see [div v1.0](https://pytorch.org/docs/1.0.0/torch.html?highlight=div#torch.div) and [div v1.8](https://pytorch.org/docs/1.8.0/generated/torch.div.html?highlight=div#torch.div)).

So the most simple solution might be replacing the `/` in [this line](https://github.com/Yinghao-Li/GuiGen/blob/22ababcd8cacae0adcc4ee74b514b188dc5084f3/TextGen/Beam.py#L66) by `//`. Another way is replacing the line by
```python
prev_beam_indices = torch.div(best_scores_id, n_vocab, rounding_mode='floor')
```

If the code still throws errors, please let me know.

P.S. This issue may also occur in other places.

**Comment by ruisi-su** [comment]
@Yinghao-Li Thanks for the help. It works now!
